version: '3.5'
volumes:
  pg_data:
  media:
  static:

services:
  foodgram_db:
    image: postgres:13.10-alpine
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5453:5432"
  backend:
    restart: always
    depends_on:
      - foodgram_db
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file: ../.env
    volumes:
      - media:/app/media
      - static:/static/
  frontend:
    depends_on:
      - foodgram_db
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    depends_on:
      - foodgram_db
    image: nginx:1.19.3
    env_file: ../.env
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/app/media